### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by RyanDyn** [sensorsdata/sensors_analytics_flutter_plugin#10]
Null safety is stable now in flutter. Any plan to migrate flutter_screen to null safety?

**Comment by GvcZhang** [comment]
> Null safety is stable now in flutter. Any plan to migrate flutter_screen to null safety?

As soon as possible to deal with it.

**Comment by hucool** [comment]
能尽快支持么，第三方引用现在剩下这个项目不支持啦。谢谢。

**Comment by GvcZhang** [comment]
> 能尽快支持么，第三方引用现在剩下这个项目不支持啦。谢谢。

您好，预计在4月22日左右会上线。

**Comment by GvcZhang** [comment]
@hucool @RyanDyn Null safety version is published, thank you for your work. 
https://pub.dev/packages/sensors_analytics_flutter_plugin
