### ISSUE TITLE
Flutter里如何采集自定义属性

### ISSUE THREAD

**Issue by kingsman2019** [sensorsdata/sensors_analytics_flutter_plugin#12]
Flutter里开启全埋点后，怎么采集自定义属性呢，有没有类似Andriod里这样的API?
![image](https://user-images.githubusercontent.com/67091997/126748385-5d3ed43c-89e5-4cc4-ad25-aa4979623f3e.png)
![image](https://user-images.githubusercontent.com/67091997/126748404-e76bf7b0-b4f0-424b-837c-38f0e4130cfa.png)

**Comment by GvcZhang** [comment]
目前没有提供这些功能。会在后续进行支持。
