### ISSUE TITLE
能否在Flutter端配置sdk初始化

### ISSUE THREAD

**Issue by BigTimo** [sensorsdata/sensors_analytics_flutter_plugin#15]
安卓和ios需要分别在原生段配置初始化信息，能否像AppsFlyer一样在Flutter配置即可
https://github.com/AppsFlyerSDK/appsflyer-flutter-plugin/blob/71b37ae40e/lib/src/appsflyer_sdk.dart#L142

**Comment by GvcZhang** [comment]
已可以初始化，添加了延迟初始化功能。
