### ISSUE TITLE
头文件引用问题

### ISSUE THREAD

**Issue by wangbiye** [sensorsdata/sensors_analytics_flutter_plugin#17]
SensorsAnalyticsFlutterPlugin.m 里边的 #import "SensorsAnalyticsSDK.h" 改成 #import <SensorsAnalyticsSDK/SensorsAnalyticsSDK.h> 吧, 通过二进制引用时会报错

**Comment by GvcZhang** [comment]
该问题应该解决了：
![image](https://user-images.githubusercontent.com/45255699/197431998-f083112d-6373-4246-a592-ab4d9000ec8c.png)

**Comment by GvcZhang** [comment]
可以再确认一下

**Comment by wangbiye** [comment]
@GvcZhang 2.2.1 版本修复了一部分, SAFlutterGlobalPropertyPlugin.h 该文件的头文件引用修改了, 但是 SensorsAnalyticsFlutterPlugin.m 没有改

**Comment by minchaozhang** [comment]
@wangbiye 实现文件中，直接导入，属于 OC 内部 import 不会引起报错

**Comment by wangbiye** [comment]
@minchaozhang 目前是把神策 SDK 打成 framework 了, 所以报错了, 需要修改为规范的外部库引用方式

**Comment by minchaozhang** [comment]
@wangbiye 建议使用 CocoaPods 或者直接源码集成 SDK

**Comment by wangbiye** [comment]
@minchaozhang 有错误应该解决错误，而不是掩耳盗铃。

**Comment by GvcZhang** [comment]
@wangbiye 你的问题是否已得到解决？

**Comment by wangbiye** [comment]
@GvcZhang 没有, 被迫 fork 了代码

**Comment by GvcZhang** [comment]
> @GvcZhang 没有, 被迫 fork 了代码

好的吧，🤷🏻‍♀️。我关掉了。
