### ISSUE TITLE
最新版本的2.2.2 Android依赖 advert-0.1.1.aar 下载不到 

### ISSUE THREAD

**Issue by lz5577** [sensorsdata/sensors_analytics_flutter_plugin#19]
> Failed to transform advert-0.1.1.aar (com.sensorsdata.analytics.android:advert:0.1.1) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find advert-0.1.1.aar (com.sensorsdata.analytics.android:advert:0.1.1).
        Searched in the following locations:
            https://maven.aliyun.com/repository/public/com/sensorsdata/analytics/android/advert/0.1.1/advert-0.1.1.aar
            https://maven.aliyun.com/repository/public/com/sensorsdata/analytics/android/advert/0.1.1/advert-0.1.1.jar
   > Failed to transform encrypt-0.1.1.aar (com.sensorsdata.analytics.android:encrypt:0.1.1) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find encrypt-0.1.1.aar (com.sensorsdata.analytics.android:encrypt:0.1.1).
        Searched in the following locations:
            https://maven.aliyun.com/repository/public/com/sensorsdata/analytics/android/encrypt/0.1.1/encrypt-0.1.1.aar
            https://maven.aliyun.com/repository/public/com/sensorsdata/analytics/android/encrypt/0.1.1/encrypt-0.1.1.jar
   > Failed to transform webview-0.1.1.aar (com.sensorsdata.analytics.android:webview:0.1.1) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find webview-0.1.1.aar (com.sensorsdata.analytics.android:webview:0.1.1).
        Searched in the following locations:
            https://maven.aliyun.com/repository/public/com/sensorsdata/analytics/android/webview/0.1.1/webview-0.1.1.aar
            https://maven.aliyun.com/repository/public/com/sensorsdata/analytics/android/webview/0.1.1/webview-0.1.1.jar

**Comment by liuweiqiang2016** [comment]
您好，请补充下你项目的仓库配置信息，示例见：
![image](https://user-images.githubusercontent.com/22735593/200985130-f725587e-3347-4a6f-aa60-bf65efaef4a7.png)
@lz5577

**Comment by lz5577** [comment]
apply from: "config.gradle"
buildscript {
    ext.kotlin_version = '1.6.10'
    repositories {
        google()
//        jcenter()
//        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/central' }
//        mavenCentral()
        maven {url 'https://developer.huawei.com/repo/'}
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlin:kotlin-android-extensions:$kotlin_version"
        classpath 'com.huawei.agconnect:agcp:1.4.1.300'
        classpath 'com.sensorsdata.analytics.android:android-gradle-plugin2:3.5.0'

    }
}

allprojects {
    repositories {
        google()
//        jcenter()
//        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/central' }
        maven {url 'https://developer.huawei.com/repo/'}
    }
    repositories {
        maven { url "https://jitpack.io" }
//        maven { url 'http://121.43.179.137:8761/repository/third_sdk_for_android/' }
    }
}

**Comment by liuweiqiang2016** [comment]
怀疑是阿里云的镜像没有把最新的版本同步过来，建议直接使用 mavenCentral()

**Comment by lz5577** [comment]
新增个 mavenCentral() 的依赖就不会报错了。 已解决~
