### ISSUE TITLE
上报的数据是加密的？

### ISSUE THREAD

**Issue by zmm2tysu** [sensorsdata/sensors_analytics_flutter_plugin#20]
我们想自己分析数据，再指定serverUrl后发现是加密的，能否取消加密我们自己来分析日志

**Comment by GvcZhang** [comment]
关于数据加密可以参考：https://manual.sensorsdata.cn/sa/latest/%E5%90%88%E8%A7%84%E8%AF%B4%E6%98%8E-22252692.html#id-%E5%90%88%E8%A7%84%E8%AF%B4%E6%98%8E-SDK%E6%9C%AC%E5%9C%B0%E6%95%B0%E6%8D%AE%E5%8A%A0%E5%AF%86

flutter 最终调用的是 native sdk，你可以直接基于 native sdk 来分析。
