### ISSUE TITLE
FlutterVisual类DynamicReceiver的unRegisterBroadcast函数报错崩溃

### ISSUE THREAD

**Issue by liugaocomeon** [sensorsdata/sensors_analytics_flutter_plugin#23]
![image](https://user-images.githubusercontent.com/19932875/225568485-b809b1e4-2920-40de-9407-a50993342534.png)
可能是多次调用的原因，应该在调用context.unregisterReceiver(mDynamicReceiver);前判断isRegister的值，防止多次调用导致上报崩溃。
![image](https://user-images.githubusercontent.com/19932875/225569228-2e4b62f8-e0c9-4d2d-bb5b-5715d097c642.png)

**Comment by GvcZhang** [comment]
感谢反馈，您是否知道如何复现，我今天测试没有复现。如果无法复现，会增加 try-catch 保护。

**Comment by liugaocomeon** [comment]
> 

我这也没复现，只是在firebase收到挺多崩溃，在发帖询问的时候是通过try-catch保护了，目前看没有新增崩溃了
![image](https://user-images.githubusercontent.com/19932875/229117032-cdc775c3-d71e-45ce-8842-3accbd386342.png)

**Comment by liuweiqiang2016** [comment]
v2.4.0 已修复
