### ISSUE TITLE
iOS的SDk使用了UIWebView导致审核不通过

### ISSUE THREAD

**Issue by huscarter** [sensorsdata/sensors_analytics_flutter_plugin#8]
查看源码在SensorsAnalyticsSDK.m中使用了UIWebView导致提交ipa包审核回执报如下问题
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

希望能更新api。

**Comment by 994914624** [comment]
你可以通过预编译宏禁用 UIWebView  @huscarter https://www.sensorsdata.cn/manual/ios_sdk_advanced.html#%E9%A2%84%E7%BC%96%E8%AF%91%E5%AE%8F%E9%85%8D%E7%BD%AE-sdk-%E7%89%B9%E6%80%A7
